name: aspect
channels:
  - conda-forge
  - defaults
dependencies:
  - myst-parser
  - sphinx-book-theme
  - sphinxcontrib-bibtex
  - cairosvg
  - pip>=20.1
  - pip:
    - sphinxcontrib-tikz
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
