name: github-docker

on: 
  push: 
    branches:
      - 'main'
  release:
    types: [created]

concurrency:
  group: docker-build
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: github.repository == 'geodynamics/aspect'
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN }}

      - name: Build and push Docker image for main
        if: contains(github.event_name, 'push')
        uses: docker/build-push-action@v4
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=ubuntu:22.04
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: geodynamics/aspect:latest

      - name: Build and push Docker image for release
        if: contains(github.event_name, 'release')
        uses: docker/build-push-action@v3
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=ubuntu:22.04
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: geodynamics/aspect:${{github.ref_name}}

